### ISSUE TITLE
i cant even describe this

### ISSUE THREAD

**Issue by pastadudes** [ProximaCentauri-star/KcalebelohVolumetrics#1]
![screenshot29](https://github.com/ProximaCentauri-star/KcalebelohVolumetrics/assets/151549235/906572eb-71ac-4ae7-8803-bcf7152e9ecc)

**Comment by pastadudes** [comment]
oh and this is on linux player, should work since blackrack just confirmed that it supports linux

**Comment by ProximaCentauri-star** [comment]
> oh and this is on linux player, should work since blackrack just confirmed that it supports linux

The config isn't updated for the latest version of EVE, might be that.
Blackrack stated that it might be caused by singularity

**Comment by pastadudes** [comment]
yeah he replied to me on patreon anyways switching to windows player fixed the issue
